export default {
    SPLASH_SCREEN: 'SplashScreen',
    INITIAL_SCREEN: 'InitialScreen',
    MY_TABS: 'MyTabs',
    MY_DRAWER: 'MyDrawer',
    LOGIN: 'Login',
    PROFILE: 'Profile',
    SIGNUP: 'Signup',
    RESET_PASSWORD: 'ResetPassword',
    MAIN_STACK:'MainStack',
    AUTH_STACK:'AuthStack',
    MY_DRAWER:'MyDrawer',
    HOME: 'Home',
    SEARCH:'Search',
    NOTEFICATION:'Notefication',
    FAVORITE:'Favorite',
    CART:'Cart',
    ITEM_DETAILS:'ItemDetails',
}